
@@ -0,0 +1,24 @@
# Generated by Django 3.2.3 on 2021-05-14 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210513_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='advisor',
        ),
        migrations.AddField(
            model_name='advisor',
            name='khiladi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aadmi', to='app.main'),
            preserve_default=False,
        ),
    ]
